name: Docker CI Learning - KUCL2
on:
  push:

jobs:
  docker-job:
    runs-on: aniket22
    steps:
      - name: Set up QEMU test
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.YASHWANT }}
          password: ${{ secrets.Ganiket }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.YASHWANT }}/nginx:githubactions

  deploy:
    needs: docker-job # Correct job name here
    name: Deploy image
    runs-on: kucl22 # Fixed the syntax; "runs-on" does not require "labels"
    steps:
      - name: Connect and pull
        run: ssh ${{ secrets.S_USER }}@${{ secrets.D_HOST }} "docker run -d ${{ secrets.DOCKERHUB_USERNAME }}/kucl22:actions"
